Repository kowainik/issue-wanted, pull requests merged in 2019-06, with the labels that each got.

#36 [#5] Add new function fetchIssuesWithLabels
  src/IW/Search.hs
  stack.yaml
Labels: api

#38 [#29] Change file structure
  Makefile
  config.toml
  issue-wanted.cabal
  sql/drop.sql
  sql/schema.sql
  src/IW/App.hs
  src/IW/App/Env.hs
  src/IW/App/Error.hs
  src/IW/App/Monad.hs
  src/IW/Config.hs
  src/IW/Db.hs
  src/IW/Db/Functions.hs
  src/IW/Db/Schema.hs
  src/IW/Effects/Log.hs
  src/IW/Server.hs
  src/IW/Server/Search.hs
  src/Prelude.hs
  stack.yaml
Labels: refactoring

#40 [#30] Describe SQL schema
  sql/drop.sql
  sql/schema.sql
  sql/seed.sql
  src/IW/Db/Functions.hs
  src/IW/Db/Issue.hs
  src/IW/Db/Repo.hs
  src/IW/Db/Schema.hs
Labels: db

#41 [#28] Wrap postgresql-simple functions
  sql/drop.sql
  src/IW/App.hs
  src/IW/App/Env.hs
  src/IW/App/Error.hs
  src/IW/App/Monad.hs
  src/IW/Db/Functions.hs
  src/IW/Effects/Log.hs
Labels: db

#44 [#26] Implement a servant endpoint
  app/Main.hs
  issue-wanted.cabal
  sql/schema.sql
  sql/seed.sql
  src/IW.hs
  src/IW/Core/Issue.hs
  src/IW/Db.hs
  src/IW/Db/Functions.hs
  src/IW/Db/Issue.hs
  src/IW/Server.hs
  src/IW/Server/Issue.hs
  src/IW/Server/Types.hs
Labels: api

#47 [#46] Add more endpoints to issue-wanted API
  sql/schema.sql
  sql/seed.sql
  src/IW/Db/Issue.hs
  src/IW/Server/Issue.hs
  src/Prelude.hs
Labels: api, question

#49 [#48] Introduce Id type with phantom type parameter
  issue-wanted.cabal
  src/IW/Core/Id.hs
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
  src/IW/Db/Issue.hs
  src/IW/Server/Issue.hs
Labels: refactoring

#53 [#50] Configure Circle CI
  .circleci/config.yml
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  issue-wanted.cabal
  stack.yaml
  test/Spec.hs
Labels: CI

#56 [#54] Update SQL schema
  sql/drop.sql
  sql/schema.sql
  sql/seed.sql
Labels: db

#66 [#51] Add instructions for testing database
  README.md
Labels: docs

#64 [#57] Update Issue type with FromRow instance using PGArray
  issue-wanted.cabal
  src/IW/Config.hs
  src/IW/Core/Issue.hs
  src/IW/Core/SqlArray.hs
Labels: refactoring

#65 [#63] Add functions for testing DB functions without running entire app
  src/IW.hs
Labels: db

#67 [#59] Update SQL query functions for Issue type
  src/IW/Db/Issue.hs
Labels: db

#72 [#70] Change name of owner column in issues table
  sql/schema.sql
  sql/seed.sql
  src/IW/Core/Issue.hs
Labels: db, refactoring

#69 [#58] Implement Repo type
  src/IW/Core/Repo.hs
Labels: db, refactoring

#77 [#76] Change fields in Issue record
  sql/schema.sql
  sql/seed.sql
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
Labels: refactoring
