Repository kowainik/issue-wanted, pull requests merged in 2019-07, with the labels that each got.

#79 [#78] Update Issue SQL schema
  sql/schema.sql
  sql/seed.sql
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
  src/IW/Db/Issue.hs
Labels: refactoring

#80 [#73] Add created_at and updated_at columns
  sql/drop.sql
  sql/schema.sql
Labels: db

#82 [#81] Update docs
  README.md
Labels: docs

#75 [#74] Setup round-trip property testing for DB
  issue-wanted.cabal
  sql/schema.sql
  src/IW/Core/Issue.hs
  src/IW/Db/Issue.hs
  stack.yaml
  test/Spec.hs
  test/Test/Assert.hs
  test/Test/Common.hs
  test/Test/Core/Issue.hs
  test/Test/Core/Repo.hs
  test/Test/Db.hs
Labels: tests, wip

#68 [#61] Add functions for inserting issues
  sql/schema.sql
  sql/seed.sql
  src/IW/Core/Issue.hs
  src/IW/Db/Issue.hs
  src/IW/Server/Issue.hs
  test/Test/Core/Issue.hs
Labels: db

#87 [#86] Add roundtrip property test for Repo
  issue-wanted.cabal
  src/IW/Core/Repo.hs
  test/Spec.hs
  test/Test/Core/Issue.hs
  test/Test/Core/Repo.hs
  test/Test/Db.hs
  test/Test/Gen.hs
Labels: tests

#88 [#85] Add unit tests for DB functions
  issue-wanted.cabal
  sql/seed.sql
  src/IW/Db.hs
  src/IW/Db/Functions.hs
  src/IW/Db/Repo.hs
  src/IW/Db/Schema.hs
  test/Spec.hs
  test/Test/Assert.hs
  test/Test/Common.hs
  test/Test/Data.hs
  test/Test/Db.hs
Labels: tests

#90 [#89] Implement WithId type
  issue-wanted.cabal
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
  src/IW/Core/WithId.hs
  src/IW/Db/Issue.hs
  src/IW/Db/Repo.hs
  src/IW/Server/Issue.hs
  test/Test/Core/Issue.hs
  test/Test/Core/Repo.hs
  test/Test/Data.hs
  test/Test/Db.hs
  test/Test/Gen.hs
Labels: question, refactoring, tests

#91 Try to speedup CI a little bit
  .circleci/config.yml
Labels: CI

#71 [#62] Implement database related functions for Repo type
  src/IW/Db/Issue.hs
  src/IW/Db/Repo.hs
Labels: db

#94 [#93] Introduce Category/Label newtypes
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
  test/Test/Core/Issue.hs
  test/Test/Core/Repo.hs
  test/Test/Data.hs
Labels: refactoring

#100 [#97] Add LIMIT 100 to DB query functions
  src/IW/Db/Issue.hs
  src/IW/Db/Repo.hs
Labels: db

#95 [#83] Implement wrapper functions around GitHub search queries
  issue-wanted.cabal
  src/IW/App/Error.hs
  src/IW/Core/Issue.hs
  src/IW/Server/Search.hs
  src/IW/Sync/Search.hs
  src/Prelude.hs
  stack.yaml
  test/Spec.hs
  test/Test/Sync.hs
Labels: github

#108 [#107] Add Url newtype for wrapping URL text
  issue-wanted.cabal
  src/IW/Core/Id.hs
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
  src/IW/Core/Url.hs
  src/IW/Sync/Search.hs
Labels: refactoring

#109 [#105] Implement `MonadDownload` effect
  issue-wanted.cabal
  src/IW.hs
  src/IW/App/Env.hs
  src/IW/Effects/Download.hs
  test/Spec.hs
  test/Test/Sync.hs
Labels: enhancement

#119 [#106] Implement MonadCabal effect
  issue-wanted.cabal
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
  src/IW/Core/Url.hs
  src/IW/Core/WithId.hs
  src/IW/Db/Functions.hs
  src/IW/Db/Issue.hs
  src/IW/Db/Repo.hs
  src/IW/Effects/Cabal.hs
  src/IW/Effects/Download.hs
  src/IW/Server/Issue.hs
  src/IW/Sync/Search.hs
  test/Test/Sync.hs
Labels: enhancement

#121 [#92] Implement better DB filter functions along with their tests
  src/IW/Db/Issue.hs
  src/IW/Db/Repo.hs
  src/IW/Server/Issue.hs
  src/Prelude.hs
  stack.yaml
  test/Test/Data.hs
  test/Test/Db.hs
Labels: db, enhancement

#123 [#104] Add functionality for associating repos with their categories
  issue-wanted.cabal
  src/IW/App/Error.hs
  src/IW/App/Monad.hs
  src/IW/Db/Repo.hs
  src/IW/Effects/Cabal.hs
  src/IW/Effects/Download.hs
  src/IW/Sync/Search.hs
  src/IW/Sync/Update.hs
  src/Prelude.hs
  stack.yaml
  test/Test/Sync.hs
Labels: db, github

#128 [#118] Use named parameters in database queries
  issue-wanted.cabal
  src/IW/App/Error.hs
  src/IW/Db/Functions.hs
  src/IW/Db/Issue.hs
  src/IW/Db/Repo.hs
  src/IW/Server/Issue.hs
  src/Prelude.hs
  stack.yaml
Labels: db, refactoring
