Repository kowainik/issue-wanted, pull requests merged in 2019-08, with the labels that each got.

#127 [#126] Implement function for fetching repos with pagination
  issue-wanted.cabal
  src/IW/App/Error.hs
  src/IW/Effects/Cabal.hs
  src/IW/Sync/Search.hs
  src/IW/Sync/Update.hs
  src/IW/Time.hs
Labels: github, refactoring, wip

#130 [#110] Remove Internal/External error wrappers used for AppErrorType
  src/IW/App/Error.hs
  src/IW/Db/Functions.hs
  src/IW/Effects/Download.hs
  test/Test/Sync.hs
Labels: backend, refactoring

#129 [#99] Add logging and error handling to `parseUserData` function
  src/IW/Sync/Search.hs
  test/Test/Sync.hs
Labels: backend, refactoring

#136 [#114] Implement proper pagination
  issue-wanted.cabal
  src/IW.hs
  src/IW/Core/Repo.hs
  src/IW/Db/Issue.hs
  src/IW/Db/Repo.hs
  src/IW/Server.hs
  src/IW/Server/Issue.hs
  src/IW/Server/Repo.hs
  test/Test/Db.hs
Labels: backend, db, refactoring

#140 [#111] Scaffold initial frontend
  README.md
  frontend/.gitignore
  frontend/elm.json
  frontend/elmapp.config.js
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/IW/Api.elm
  frontend/src/IW/Core/Decoder.elm
  frontend/src/IW/Core/ElmStreet.elm
  frontend/src/IW/Core/Encoder.elm
  frontend/src/IW/Core/Types.elm
  frontend/src/Main.elm
  frontend/src/index.js
  frontend/src/main.css
  frontend/src/registerServiceWorker.js
  generate-elm/Main.hs
  issue-wanted.cabal
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
  src/IW/Core/SqlArray.hs
  src/Prelude.hs
  stack.yaml
Labels: frontend

#131 [#120] Add repoCabalUrl field to Repo type
  sql/schema.sql
  src/IW/Core/Issue.hs
  src/IW/Core/Repo.hs
  src/IW/Core/Url.hs
  src/IW/Db/Repo.hs
  src/IW/Effects/Cabal.hs
  src/IW/Sync/Search.hs
  src/IW/Sync/Update.hs
  test/Test/Core/Repo.hs
  test/Test/Data.hs
  test/Test/Sync.hs
Labels: refactoring

#143 [#141] Add frontend check to CI
  .circleci/config.yml
Labels: CI

#142 [#102] Add handling of cabal file parse errors
  src/IW/App/Error.hs
  src/IW/Core/Repo.hs
  src/IW/Effects/Cabal.hs
  src/IW/Effects/Download.hs
  test/Test/Sync.hs
Labels: backend, refactoring

#148 [#122] Update README
  README.md
Labels: docs
